### ISSUE TITLE
Facebook Custom Chat Plugin

### ISSUE THREAD

**Issue by judewang** [tmotx/cymking#10]
- [x] 嵌入 sdk 與 plugin
- [x] facebook page 設定
- [x] facebook app 設定
- [ ] facebook app 審查

**Comment by judewang** [comment]
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/1559819/48066698-a841b500-e211-11e8-8419-e6553782c8d4.png">

**Comment by judewang** [comment]
審查尚缺符合規格的 app icon，等 @ida500162 明天提供

**Comment by ida500162** [comment]
@judewang  
icon 連結
https://drive.google.com/open?id=1zLloaeX-Gzio1DkirLmJT8uY9gVYmAOM

**Comment by judewang** [comment]
沒有要寫 messenger bot 暫不送審
