### ISSUE TITLE
更新價目表

### ISSUE THREAD

**Issue by yutin1987** [tmotx/cymking#16]
<img width="597" alt="2018-11-20 10 40 38" src="https://user-images.githubusercontent.com/2505934/48748939-9e10c380-ecb3-11e8-9753-729dea4f54e9.png">

**Comment by ida500162** [comment]
@judewang 
更新價目表 
![1542775342095](https://user-images.githubusercontent.com/44158114/48819452-f961b500-ed8a-11e8-9d29-df52bd67cf7a.jpg)

![1542775318457](https://user-images.githubusercontent.com/44158114/48819463-02528680-ed8b-11e8-96c5-f6a068333b86.jpg)

更新sketch檔 連結
https://drive.google.com/open?id=1KxTzNGyvbjaqq4FZIZLI04CihgHCgMaf

**Comment by judewang** [comment]
done
