### ISSUE TITLE
修正行事曆

### ISSUE THREAD

**Issue by yutin1987** [tmotx/cymking#18]
- [x] 從行事曆上點擊 booking 使用連結 `https://docs.google.com/forms/d/e/1FAIpQLSeHXe_B-HvzHIzTMZUe_9ycjmdGNhlv55bj9YYOG7UO9ccrnA/viewform?entry.1887716854=2018-01-01` 預先輸入日期
- [x] 選擇該日期時，圈選的圓圈似乎沒有置中
- [x] 該日期 [沒有預約] 或 [已有預約] ，應該都要可以點擊且可以預約，避免誤解`已預約的日期無法預約其他時段`

**Comment by judewang** [comment]
@ida500162 第三點「已有預約」的狀況下該怎麼放 booking 按鈕？希望可以提供一下示意圖

**Comment by ida500162** [comment]
@judewang  示意圖

![01](https://user-images.githubusercontent.com/44158114/48928323-c6e5c280-ef18-11e8-92a9-70c46f2c1531.jpg)

![02](https://user-images.githubusercontent.com/44158114/48928324-cd743a00-ef18-11e8-9faf-28e2cd8860aa.jpg)



sketch 更新檔
https://drive.google.com/open?id=1KxTzNGyvbjaqq4FZIZLI04CihgHCgMaf
