### ISSUE TITLE
[Refactor] cymking 首頁改版

### ISSUE THREAD

**Issue by charlieworld** [tmotx/cymking#25]
### 頁面 Zeplin 連結
https://app.zeplin.io/project/5c81e7f5081f474d00bb19cf/screen/5cfde93c0350be5d44928e05

### 文字說明 Zeplin 連結
https://app.zeplin.io/project/5c81e7f5081f474d00bb19cf/screen/5cfde9988b72df5e28e34661

###  素材
https://drive.google.com/drive/folders/1JrUtDqjFYBFCuVlp5CY9cjGSEQdNE_dX

##  網頁工程使用技術

-  CSS 框架使用 "[pure css](https://purecss.io/)"

**Comment by ida500162** [comment]
###  素材 額外服務/軟硬體設備 icon

https://drive.google.com/open?id=16FPQMR2CEc9Wa1mjUYFKDD4jcXnKh3Yd
