### ISSUE TITLE
不要使用 meetup 的 logo

### ISSUE THREAD

**Issue by yutin1987** [tmotx/cymking#3]
由於目前確認，不一定會使用 meetup 的平台，因此不使用 meetup 的 logo ，另外設計確保整體視覺的一致性
![f85865ae-3659-45c0-bf88-ce44da7dc297](https://user-images.githubusercontent.com/2505934/47829905-99e43b00-ddc4-11e8-83d3-e031c552b1d6.jpeg)

**Comment by judewang** [comment]
done https://github.com/tmotx/cymking/pull/2/commits/bbc67df885c664005ef64b728ca9704c481e2cb8
