### ISSUE TITLE
收費模式 分為 2 + 1

### ISSUE THREAD

**Issue by yutin1987** [tmotx/cymking#4]
![8ce31e58-9faa-44b6-9bbf-73d547e8691c](https://user-images.githubusercontent.com/2505934/47829982-e7f93e80-ddc4-11e8-9028-21ead91cbebc.jpeg)

沙發：
平日 5pm ~ 10pm 50元 / 人 ，不限時
假日 10am ~ 10pm 100元 / 人 ，不限時

Gallery：
Email 來信詢問

沙發區特別提示：提供 4K 50吋 電視

**Comment by judewang** [comment]
@ida500162 設計修改完再 assign 我接手開發哦

**Comment by ida500162** [comment]
done

**Comment by judewang** [comment]
程式還沒更新😅
