### ISSUE TITLE
修改 facebook opengraph image

### ISSUE THREAD

**Issue by judewang** [tmotx/cymking#5]
目前的預覽圖跟 `logo-fb.jpg` 的比例不合，會被裁切到

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/1559819/47840224-f5c8b700-ddf8-11e8-9cb6-ac32a4975717.png">

**Comment by ida500162** [comment]
facebook opengraph image 圖檔上傳

Fb_share
https://drive.google.com/open?id=19zhtgcS6QtEvjRoTaP4--LOyE9FdkE3d

**Comment by ida500162** [comment]
done

**Comment by judewang** [comment]
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/1559819/47997270-96431200-e13e-11e8-8c48-f18f649de260.png">
