### ISSUE TITLE
增加 footer

### ISSUE THREAD

**Issue by yutin1987** [tmotx/cymking#6]
footer 裡面寫
```
Cymking Space | 集界科技股份有限公司
space@tmotx.com
115 台北市南港區南港路三段 52 號 7 樓
```

**Comment by judewang** [comment]
@ida500162 我先自己試做了一下，你看一下需不需要調整樣式，需要的話妳把 sketch 更新之後再 assing 給我，不需要的話這個 issue 可以留給我 close

<img width="992" alt="image" src="https://user-images.githubusercontent.com/1559819/47985582-70594580-e11d-11e8-90a8-ae6092f37455.png">

**Comment by ida500162** [comment]
@judewang 

sketch 更新好了 footer只做了一些微調
然後
head、收費區 、行事曆 區文字
“Meet up” 統一更改為“Meetup”

更新檔
https://drive.google.com/open?id=1a8WZGxxCf_Yr_7hm9K6BgVAo4B0WHqjM

**Comment by judewang** [comment]
@ida500162 sketch 檔案下午更新再開啟之後很多圖層變的殘破不堪，能幫我確認一下你那邊有沒有問題嗎？

![](https://jude.d.pr/jMpoSv+)

About 先前的調整也不見了

**Comment by ida500162** [comment]
@judewang  我家裡的電腦下載看沒有問題 東西都健在
![1541424062894](https://user-images.githubusercontent.com/44158114/48000555-c390bf80-e140-11e8-9963-3a48edd54f40.jpg)

**Comment by judewang** [comment]
#14
